language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo pip install pytest"
  - "sudo pip install -r requirements.txt"
# command to run tests
script: "cd src; sudo python -m pytest;"
notifications:
  email:
    - ahmed.kachkach@gmail.com
